name: Test

on:
  push:
    branches:
      - main
      - feature/**

jobs:
  Test:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install java 11 (Temurin)
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Set up Maven 3.8.4
        uses: stCarolas/setup-maven@v4.2
        with:
          maven-version: 3.8.4
      - name: Test backend
        working-directory: ./backend
        run: mvn clean test
      - name: Setup dotNet (ta mere tmtc)
        uses: actions/setup-dotnet@v1
          with:
            dotnet-version: |
              3.1.x
              5.0.x
      - name: Test frontend
        working-directory: ./dotNet
        run: dotnet test ./
      - name: Test cli
        working-directory: ./cli
        run: mvn clean test
      - name: Generate the backend coverage badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: backend/target/site/jacoco/jacoco.csv
          coverage-badge-filename: backend-jacoco.svg
      - name: Commit the backend badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated backend JaCoCo coverage badge"
            git push
          fi
      - name: Generate the frontend coverage badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: dotNet/target/site/jacoco/jacoco.csv
          coverage-badge-filename: frontend-jacoco.svg
      - name: Commit the frontend badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated frontend JaCoCo coverage badge"
            git push
          fi
      - name: Generate the cli coverage badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          jacoco-csv-file: cli/target/site/jacoco/jacoco.csv
          coverage-badge-filename: cli-jacoco.svg
      - name: Commit the cli badge (if it changed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'github-actions'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated cli JaCoCo coverage badge"
            git push
          fi